/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.biblioteca.views;

import bibliotecaTest1.*;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author angel
 */
public class Socios extends javax.swing.JPanel {
    private static Biblioteca biblioteca;

    /**
     * Creates new form Socios
     */
    public Socios(Biblioteca b) {
        initComponents();
        this.biblioteca=b;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nombreBarra = new javax.swing.JTextField();
        buscarBoton = new javax.swing.JPanel();
        buscarTxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sociosTabla = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setText("Socios");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        nombreBarra.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        nombreBarra.setForeground(new java.awt.Color(204, 204, 204));
        nombreBarra.setText("Ingrese el nombre del socio");
        nombreBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreBarraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nombreBarra, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nombreBarra, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        buscarBoton.setBackground(new java.awt.Color(0, 60, 94));
        buscarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarBotonMouseClicked(evt);
            }
        });

        buscarTxt.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        buscarTxt.setForeground(new java.awt.Color(255, 255, 255));
        buscarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buscarTxt.setText("BUSCAR");
        buscarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buscarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buscarBotonLayout = new javax.swing.GroupLayout(buscarBoton);
        buscarBoton.setLayout(buscarBotonLayout);
        buscarBotonLayout.setHorizontalGroup(
            buscarBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        );
        buscarBotonLayout.setVerticalGroup(
            buscarBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sociosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Dirección", "Numero de prestamos", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(sociosTabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(buscarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(318, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buscarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreBarraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreBarraMouseClicked
          nombreBarra.setText("");
    }//GEN-LAST:event_nombreBarraMouseClicked

    private void buscarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarTxtMouseEntered
        buscarBoton.setBackground(new Color(31,128,173));
    }//GEN-LAST:event_buscarTxtMouseEntered

    private void buscarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarTxtMouseExited
        buscarBoton.setBackground(new Color(0,60,94));
    }//GEN-LAST:event_buscarTxtMouseExited

    private void buscarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarTxtMouseClicked
        if(nombreBarra.getText().isEmpty()){
            ArrayList<Socio> socios = new ArrayList<Socio>();
            socios = biblioteca.sociosTabla();
            int i=0;
            for(Socio socio : socios){
                sociosTabla.setValueAt(socio.getNombreSocio(), i, 0);
                sociosTabla.setValueAt(socio.getDireccion(),i,1);
                sociosTabla.setValueAt(socio.getNumPrestados(), i, 2);
                sociosTabla.setValueAt(socio.getNumeroSocio(), i, 3);
                i++;
            } 
        }else{
            try{
                Socio socio = biblioteca.nombreBuscado(nombreBarra.getText());
                sociosTabla.setValueAt(socio.getNombreSocio(), 0, 0);
                sociosTabla.setValueAt(socio.getDireccion(),0,1);
                sociosTabla.setValueAt(socio.getNumPrestados(), 0, 2);
                sociosTabla.setValueAt(socio.getNumeroSocio(), 0, 3);
            }catch (ESocioNoEncontrado e){
                javax.swing.JOptionPane.showMessageDialog(this,"No se tiene registro del socio","ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_buscarTxtMouseClicked

    private void buscarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBotonMouseClicked
        if(nombreBarra.getText().isEmpty()){
            ArrayList<Socio> socios = new ArrayList<Socio>();
            socios = biblioteca.sociosTabla();
            int i=0;
            for(Socio socio : socios){
                sociosTabla.setValueAt(socio.getNombreSocio(), i, 0);
                sociosTabla.setValueAt(socio.getDireccion(),i,1);
                sociosTabla.setValueAt(socio.getNumPrestados(), i, 2);
                sociosTabla.setValueAt(socio.getNumeroSocio(), i, 3);
                i++;
            }
        }else{
            try{
                Socio socio = biblioteca.nombreBuscado(nombreBarra.getText());
                sociosTabla.setValueAt(socio.getNombreSocio(), 0, 0);
                sociosTabla.setValueAt(socio.getDireccion(),0,1);
                sociosTabla.setValueAt(socio.getNumPrestados(), 0, 2);
                sociosTabla.setValueAt(socio.getNumeroSocio(), 0, 3);
            }catch (ESocioNoEncontrado e){
                javax.swing.JOptionPane.showMessageDialog(this,"No se tiene registro del socio","ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_buscarBotonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buscarBoton;
    private javax.swing.JLabel buscarTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreBarra;
    private javax.swing.JTable sociosTabla;
    // End of variables declaration//GEN-END:variables
}
